[build]
command = "npm run build"
publish = "frontend/.next"
functions = "netlify/functions"


[[redirects]]
from = "/api/*"
to = "https://<your-render-service>.onrender.com/:splat"
status = 200
force = true
